name: Simple GitHub Pages Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build React App
        run: |
          echo "Building React app for GitHub Pages..."
          NODE_ENV=production npx vite build --outDir dist --base /JrgWebsite/ --mode production
          
          # Verify build succeeded
          if [ ! -d "dist" ]; then
            echo "Build failed - dist directory not created"
            exit 1
          fi
          
          if [ ! -f "dist/index.html" ]; then
            echo "Build failed - index.html not found"
            exit 1
          fi
          
          echo "Build successful. Contents:"
          ls -la dist/
          
      - name: Copy additional files
        run: |
          # Ensure dist directory exists
          mkdir -p dist
          
          # Copy 404.html if it exists
          if [ -f "public/404.html" ]; then
            cp public/404.html dist/
          fi
          
          # Copy assets if they exist
          if [ -d "attached_assets" ]; then
            mkdir -p dist/attached_assets
            cp -r attached_assets/* dist/attached_assets/ 2>/dev/null || true
          fi
          
          # Copy video files if they exist
          if ls public/*.mp4 1> /dev/null 2>&1; then
            cp public/*.mp4 dist/ || true
          fi
          
          echo "Files copied successfully"
          ls -la dist/
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4